### ISSUE TITLE
MILESTONE -V1 FRIENDSHIP

### ISSUE THREAD

**Issue by ChristianOtieno** [ChristianOtieno/rails-facebook#6]

**Comment by Chincoya** [comment]
[That file](https://github.com/ChristianOtieno/rails-facebook/blob/feature/milestone-5/app/views/users/index.html.erb)

Assign @friendship to an actual object in the database, so ypou can use it's id as a route for patching or deleting. 
Lines [47](https://github.com/ChristianOtieno/rails-facebook/blob/0661ce5ec39bf834447e87e0750e7fbf103dbe65/app/views/users/index.html.erb#L47)
And [48](https://github.com/ChristianOtieno/rails-facebook/blob/0661ce5ec39bf834447e87e0750e7fbf103dbe65/app/views/users/index.html.erb#L48)

**Comment by ChristianOtieno** [comment]
Thanks for the heads-up I just solved it in some interesting way.
